<hark_xml>
  <hark_config id="TSPList" major="2" minor="0">
    <SynchronousAverage>16</SynchronousAverage>
    <OriginalImpulseFile type="float">/bin/harktool4_utils/16384.little_endian.tsp</OriginalImpulseFile>
    <TSPOffset>16384</TSPOffset>
    <TSPLength>16384</TSPLength>
    <SignalMax>32768</SignalMax>
    <NumMic>8</NumMic>
    <SourceFileType>float</SourceFileType>
    <Comment>created by harktool4</Comment>
    <Sources size="144">
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-1.0000</X>
          <Y>0.0000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D180_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-1.0000</X>
          <Y>0.0000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D180_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9962</X>
          <Y>-0.0872</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D185_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9962</X>
          <Y>-0.0872</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D185_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9848</X>
          <Y>-0.1736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D190_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9848</X>
          <Y>-0.1736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D190_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9659</X>
          <Y>-0.2588</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D195_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9659</X>
          <Y>-0.2588</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D195_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9397</X>
          <Y>-0.3420</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D200_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9397</X>
          <Y>-0.3420</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D200_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9063</X>
          <Y>-0.4226</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D205_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9063</X>
          <Y>-0.4226</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D205_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8660</X>
          <Y>-0.5000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D210_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8660</X>
          <Y>-0.5000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D210_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8192</X>
          <Y>-0.5736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D215_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8192</X>
          <Y>-0.5736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D215_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7660</X>
          <Y>-0.6428</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D220_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7660</X>
          <Y>-0.6428</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D220_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7071</X>
          <Y>-0.7071</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D225_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7071</X>
          <Y>-0.7071</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D225_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.6428</X>
          <Y>-0.7660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D230_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.6428</X>
          <Y>-0.7660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D230_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5736</X>
          <Y>-0.8192</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D235_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5736</X>
          <Y>-0.8192</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D235_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5000</X>
          <Y>-0.8660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D240_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5000</X>
          <Y>-0.8660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D240_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.4226</X>
          <Y>-0.9063</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D245_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.4226</X>
          <Y>-0.9063</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D245_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.3420</X>
          <Y>-0.9397</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D250_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.3420</X>
          <Y>-0.9397</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D250_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.2588</X>
          <Y>-0.9659</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D255_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.2588</X>
          <Y>-0.9659</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D255_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.1736</X>
          <Y>-0.9848</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D260_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.1736</X>
          <Y>-0.9848</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D260_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.0872</X>
          <Y>-0.9962</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D265_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.0872</X>
          <Y>-0.9962</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D265_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.0000</X>
          <Y>-1.0000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D270_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.0000</X>
          <Y>-1.0000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D270_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.0872</X>
          <Y>-0.9962</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D275_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.0872</X>
          <Y>-0.9962</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D275_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.1736</X>
          <Y>-0.9848</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D280_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.1736</X>
          <Y>-0.9848</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D280_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.2588</X>
          <Y>-0.9659</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D285_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.2588</X>
          <Y>-0.9659</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D285_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.3420</X>
          <Y>-0.9397</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D290_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.3420</X>
          <Y>-0.9397</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D290_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.4226</X>
          <Y>-0.9063</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D295_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.4226</X>
          <Y>-0.9063</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D295_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5000</X>
          <Y>-0.8660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D300_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5000</X>
          <Y>-0.8660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D300_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5736</X>
          <Y>-0.8192</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D305_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5736</X>
          <Y>-0.8192</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D305_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.6428</X>
          <Y>-0.7660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D310_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.6428</X>
          <Y>-0.7660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D310_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7071</X>
          <Y>-0.7071</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D315_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7071</X>
          <Y>-0.7071</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D315_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7660</X>
          <Y>-0.6428</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D320_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7660</X>
          <Y>-0.6428</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D320_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8192</X>
          <Y>-0.5736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D325_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8192</X>
          <Y>-0.5736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D325_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8660</X>
          <Y>-0.5000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D330_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8660</X>
          <Y>-0.5000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D330_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9063</X>
          <Y>-0.4226</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D335_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9063</X>
          <Y>-0.4226</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D335_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9397</X>
          <Y>-0.3420</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D340_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9397</X>
          <Y>-0.3420</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D340_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9659</X>
          <Y>-0.2588</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D345_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9659</X>
          <Y>-0.2588</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D345_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9848</X>
          <Y>-0.1736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D350_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9848</X>
          <Y>-0.1736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D350_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9962</X>
          <Y>-0.0872</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D355_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9962</X>
          <Y>-0.0872</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D355_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>1.0000</X>
          <Y>0.0000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D000_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>1.0000</X>
          <Y>0.0000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D000_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9962</X>
          <Y>0.0872</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D005_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9962</X>
          <Y>0.0872</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D005_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9848</X>
          <Y>0.1736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D010_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9848</X>
          <Y>0.1736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D010_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9659</X>
          <Y>0.2588</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D015_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9659</X>
          <Y>0.2588</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D015_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9397</X>
          <Y>0.3420</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D020_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9397</X>
          <Y>0.3420</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D020_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9063</X>
          <Y>0.4226</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D025_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.9063</X>
          <Y>0.4226</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D025_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8660</X>
          <Y>0.5000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D030_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8660</X>
          <Y>0.5000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D030_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8192</X>
          <Y>0.5736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D035_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.8192</X>
          <Y>0.5736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D035_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7660</X>
          <Y>0.6428</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D040_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7660</X>
          <Y>0.6428</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D040_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7071</X>
          <Y>0.7071</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D045_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.7071</X>
          <Y>0.7071</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D045_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.6428</X>
          <Y>0.7660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D050_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.6428</X>
          <Y>0.7660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D050_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5736</X>
          <Y>0.8192</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D055_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5736</X>
          <Y>0.8192</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D055_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5000</X>
          <Y>0.8660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D060_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.5000</X>
          <Y>0.8660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D060_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.4226</X>
          <Y>0.9063</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D065_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.4226</X>
          <Y>0.9063</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D065_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.3420</X>
          <Y>0.9397</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D070_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.3420</X>
          <Y>0.9397</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D070_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.2588</X>
          <Y>0.9659</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D075_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.2588</X>
          <Y>0.9659</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D075_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.1736</X>
          <Y>0.9848</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D080_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.1736</X>
          <Y>0.9848</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D080_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.0872</X>
          <Y>0.9962</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D085_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.0872</X>
          <Y>0.9962</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D085_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.0000</X>
          <Y>1.0000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D090_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>0.0000</X>
          <Y>1.0000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D090_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.0872</X>
          <Y>0.9962</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D095_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.0872</X>
          <Y>0.9962</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D095_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.1736</X>
          <Y>0.9848</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D100_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.1736</X>
          <Y>0.9848</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D100_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.2588</X>
          <Y>0.9659</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D105_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.2588</X>
          <Y>0.9659</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D105_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.3420</X>
          <Y>0.9397</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D110_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.3420</X>
          <Y>0.9397</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D110_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.4226</X>
          <Y>0.9063</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D115_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.4226</X>
          <Y>0.9063</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D115_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5000</X>
          <Y>0.8660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D120_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5000</X>
          <Y>0.8660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D120_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5736</X>
          <Y>0.8192</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D125_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.5736</X>
          <Y>0.8192</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D125_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.6428</X>
          <Y>0.7660</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D130_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.6428</X>
          <Y>0.7660</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D130_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7071</X>
          <Y>0.7071</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D135_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7071</X>
          <Y>0.7071</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D135_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7660</X>
          <Y>0.6428</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D140_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.7660</X>
          <Y>0.6428</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D140_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8192</X>
          <Y>0.5736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D145_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8192</X>
          <Y>0.5736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D145_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8660</X>
          <Y>0.5000</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D150_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.8660</X>
          <Y>0.5000</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D150_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9063</X>
          <Y>0.4226</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D155_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9063</X>
          <Y>0.4226</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D155_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9397</X>
          <Y>0.3420</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D160_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9397</X>
          <Y>0.3420</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D160_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9659</X>
          <Y>0.2588</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D165_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9659</X>
          <Y>0.2588</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D165_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9848</X>
          <Y>0.1736</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D170_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9848</X>
          <Y>0.1736</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D170_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9962</X>
          <Y>0.0872</Y>
          <Z>0.0000</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D175_H000_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
      <Source>
        <Position unit="meter" type="cartesian">
          <X>-0.9962</X>
          <Y>0.0872</Y>
          <Z>0.0100</Z>
        </Position>
        <Files size="1">
          <File>
            <Name>/home/alex/D175_H010_R100.wav</Name>
            <MicIndices size="8">
              <MicIndex>0</MicIndex>
              <MicIndex>1</MicIndex>
              <MicIndex>2</MicIndex>
              <MicIndex>3</MicIndex>
              <MicIndex>4</MicIndex>
              <MicIndex>5</MicIndex>
              <MicIndex>6</MicIndex>
              <MicIndex>7</MicIndex>
            </MicIndices>
          </File>
        </Files>
        <CutStart>1</CutStart>
        <CutEnd>0</CutEnd>
      </Source>
    </Sources>
  </hark_config>
</hark_xml>
